version: '3'
services:
  app:
    image: node:lts
    user: node:node
    container_name: front-public-nuxt
    working_dir: /app
    volumes:
      - ./:/app
    networks:
      - nuxt
    environment:
      HOST: 0.0.0.0
    ports:
      - '8081:3000'
    command: npm run dev

networks:
  nuxt:
    driver: bridge
